from fastapi import APIRouter
from pydantic import BaseModel

from app.services.schema_service import get_schema
from app.services.ollama_service import generate_sql
from app.services.db_service import execute_query
from app.utils.sql_validator import validate_sql

router = APIRouter()


class Prompt(BaseModel):
    question: str


@router.post("/text2sql")
def text2sql(prompt: Prompt):

    schema = get_schema()

    sql = generate_sql(
    schema,
    prompt.question,
    )

    print("=" * 60)
    print(sql)
    print("=" * 60)

    validate_sql(sql)

    from fastapi import HTTPException

    try:
        result = execute_query(sql)
    except Exception as e:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid SQL generated by AI: {str(e)}"
        )

    return {
        "question": prompt.question,
        "sql": sql,
        "result": result,
    }